"""initial migration

Revision ID: a367db6e90ec
Revises: 
Create Date: 2024-05-15 17:35:48.873217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a367db6e90ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('online_only')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online_only', sa.BOOLEAN(), nullable=True))

    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activities', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
